// Dados fictícios usados quando não há Supabase configurado (VITE_SUPABASE_URL ausente) —
// permitem demonstrar o fluxo completo do cardápio/pedido sem depender do banco.
// Quando o banco for implementado, o mesmo formato deve ser refletido em
// supabase/migrations/0003_item_options.sql + seed.
import type { Business, MenuCategory, MenuItem, PlanFeatureRow } from './types'

export const MOCK_BUSINESS: Business = {
  id: 'mock-business-burger-do-ze',
  owner_id: 'mock-owner',
  name: 'Burger do Zé',
  slug: 'burger-do-ze',
  type: 'hamburgueria',
  plan: 'premium',
  theme_config: { accent: '#f97316' },
  lat: -1.4558,
  lng: -48.4902,
  is_open: true,
  created_at: new Date().toISOString(),
  description: 'Hambúrgueres artesanais feitos na hora, no coração de Belém.',
  address: 'Tv. Padre Eutíquio, 1200 — Batista Campos, Belém-PA',
  neighborhood: 'Batista Campos',
  phone: '(91) 99999-0000',
  opening_hours: 'Ter a Dom, 18h às 23h',
  logo_url: null,
}

export const MOCK_CATEGORIES: MenuCategory[] = [
  { id: 'cat-lanches', business_id: MOCK_BUSINESS.id, name: 'Lanches', order_index: 0 },
  { id: 'cat-acompanhamentos', business_id: MOCK_BUSINESS.id, name: 'Acompanhamentos', order_index: 1 },
  { id: 'cat-bebidas', business_id: MOCK_BUSINESS.id, name: 'Bebidas', order_index: 2 },
]

const PONTO_DA_CARNE = {
  id: 'grp-ponto',
  name: 'Ponto da carne',
  required: true,
  multiple: false,
  choices: [
    { id: 'ponto-mal', name: 'Mal passado', price_delta: 0 },
    { id: 'ponto-ao-ponto', name: 'Ao ponto', price_delta: 0 },
    { id: 'ponto-bem', name: 'Bem passado', price_delta: 0 },
  ],
}

const ADICIONAIS = {
  id: 'grp-adicionais',
  name: 'Adicionais',
  required: false,
  multiple: true,
  choices: [
    { id: 'add-bacon', name: '+ Bacon', price_delta: 4 },
    { id: 'add-ovo', name: '+ Ovo', price_delta: 3 },
    { id: 'add-cheddar', name: '+ Cheddar extra', price_delta: 3 },
    { id: 'add-molho', name: '+ Molho especial', price_delta: 2 },
  ],
}

export const MOCK_ITEMS: MenuItem[] = [
  {
    id: 'item-cheddar-duplo',
    business_id: MOCK_BUSINESS.id,
    category_id: 'cat-lanches',
    name: 'Cheddar Duplo',
    description: 'Dois hambúrgueres, cheddar cremoso, picles e molho da casa.',
    price: 28.9,
    image_url: null,
    is_available: true,
    order_index: 0,
    option_groups: [PONTO_DA_CARNE, ADICIONAIS],
  },
  {
    id: 'item-x-salada',
    business_id: MOCK_BUSINESS.id,
    category_id: 'cat-lanches',
    name: 'X-Salada Simples',
    description: 'Hambúrguer, queijo, alface, tomate e maionese da casa.',
    price: 19.9,
    image_url: null,
    is_available: true,
    order_index: 1,
    option_groups: [PONTO_DA_CARNE, ADICIONAIS],
  },
  {
    id: 'item-x-bacon',
    business_id: MOCK_BUSINESS.id,
    category_id: 'cat-lanches',
    name: 'X-Bacon',
    description: 'Hambúrguer, queijo, bacon crocante e molho barbecue.',
    price: 24.9,
    image_url: null,
    is_available: true,
    order_index: 2,
    option_groups: [PONTO_DA_CARNE, ADICIONAIS],
  },
  {
    id: 'item-batata-cheddar-bacon',
    business_id: MOCK_BUSINESS.id,
    category_id: 'cat-acompanhamentos',
    name: 'Batata Cheddar Bacon',
    description: 'Porção de batata frita com cheddar cremoso e bacon.',
    price: 22.0,
    image_url: null,
    is_available: true,
    order_index: 0,
  },
  {
    id: 'item-batata-simples',
    business_id: MOCK_BUSINESS.id,
    category_id: 'cat-acompanhamentos',
    name: 'Batata Frita Simples',
    description: 'Porção generosa de batata frita crocante.',
    price: 14.9,
    image_url: null,
    is_available: true,
    order_index: 1,
  },
  {
    id: 'item-onion-rings',
    business_id: MOCK_BUSINESS.id,
    category_id: 'cat-acompanhamentos',
    name: 'Onion Rings',
    description: 'Anéis de cebola empanados, crocantes por fora.',
    price: 16.9,
    image_url: null,
    is_available: true,
    order_index: 2,
  },
  {
    id: 'item-milkshake-ovomaltine',
    business_id: MOCK_BUSINESS.id,
    category_id: 'cat-bebidas',
    name: 'Milk Shake Ovomaltine',
    description: 'Cremoso, com calda e granulado de Ovomaltine.',
    price: 18.0,
    image_url: null,
    is_available: true,
    order_index: 0,
  },
  {
    id: 'item-refrigerante',
    business_id: MOCK_BUSINESS.id,
    category_id: 'cat-bebidas',
    name: 'Refrigerante Lata',
    description: 'Coca-Cola, Guaraná ou Sprite — 350ml.',
    price: 6.0,
    image_url: null,
    is_available: true,
    order_index: 1,
  },
  {
    id: 'item-suco-natural',
    business_id: MOCK_BUSINESS.id,
    category_id: 'cat-bebidas',
    name: 'Suco Natural',
    description: 'Cupuaçu, maracujá ou abacaxi com hortelã.',
    price: 9.9,
    image_url: null,
    is_available: true,
    order_index: 2,
  },
  {
    id: 'item-agua',
    business_id: MOCK_BUSINESS.id,
    category_id: 'cat-bebidas',
    name: 'Água Mineral',
    description: 'Com ou sem gás — 500ml.',
    price: 4.0,
    image_url: null,
    is_available: true,
    order_index: 3,
  },
]

// Mesmo conteúdo de supabase/migrations/0002_seed.sql — mantido em sincronia manualmente
// até existir um projeto Supabase configurado (ver SETUP.md).
export const MOCK_PLAN_FEATURES: PlanFeatureRow[] = [
  { plan: 'free', feature_key: 'cardapio_digital', enabled: true, usage_limit: null },
  { plan: 'free', feature_key: 'pedido_retirada', enabled: true, usage_limit: 30 },
  { plan: 'free', feature_key: 'pedido_local', enabled: false, usage_limit: null },
  { plan: 'free', feature_key: 'delivery', enabled: false, usage_limit: null },
  { plan: 'free', feature_key: 'instalacao_proximidade', enabled: true, usage_limit: 100 },
  { plan: 'free', feature_key: 'logo_propria', enabled: false, usage_limit: null },
  { plan: 'free', feature_key: 'identidade_completa', enabled: false, usage_limit: null },
  { plan: 'free', feature_key: 'push_notifications', enabled: false, usage_limit: null },
  { plan: 'free', feature_key: 'analytics_basico', enabled: false, usage_limit: null },
  { plan: 'free', feature_key: 'analytics_avancado', enabled: false, usage_limit: null },
  { plan: 'free', feature_key: 'multiplas_unidades', enabled: false, usage_limit: null },

  { plan: 'basico', feature_key: 'cardapio_digital', enabled: true, usage_limit: null },
  { plan: 'basico', feature_key: 'pedido_retirada', enabled: true, usage_limit: null },
  { plan: 'basico', feature_key: 'pedido_local', enabled: true, usage_limit: null },
  { plan: 'basico', feature_key: 'delivery', enabled: true, usage_limit: null },
  { plan: 'basico', feature_key: 'instalacao_proximidade', enabled: true, usage_limit: 300 },
  { plan: 'basico', feature_key: 'logo_propria', enabled: true, usage_limit: null },
  { plan: 'basico', feature_key: 'identidade_completa', enabled: false, usage_limit: null },
  { plan: 'basico', feature_key: 'push_notifications', enabled: false, usage_limit: null },
  { plan: 'basico', feature_key: 'analytics_basico', enabled: true, usage_limit: null },
  { plan: 'basico', feature_key: 'analytics_avancado', enabled: false, usage_limit: null },
  { plan: 'basico', feature_key: 'multiplas_unidades', enabled: false, usage_limit: null },

  { plan: 'premium', feature_key: 'cardapio_digital', enabled: true, usage_limit: null },
  { plan: 'premium', feature_key: 'pedido_retirada', enabled: true, usage_limit: null },
  { plan: 'premium', feature_key: 'pedido_local', enabled: true, usage_limit: null },
  { plan: 'premium', feature_key: 'delivery', enabled: true, usage_limit: null },
  { plan: 'premium', feature_key: 'instalacao_proximidade', enabled: true, usage_limit: 500 },
  { plan: 'premium', feature_key: 'logo_propria', enabled: true, usage_limit: null },
  { plan: 'premium', feature_key: 'identidade_completa', enabled: true, usage_limit: null },
  { plan: 'premium', feature_key: 'push_notifications', enabled: true, usage_limit: null },
  { plan: 'premium', feature_key: 'analytics_basico', enabled: true, usage_limit: null },
  { plan: 'premium', feature_key: 'analytics_avancado', enabled: true, usage_limit: null },
  { plan: 'premium', feature_key: 'multiplas_unidades', enabled: true, usage_limit: null },
]
